const dummyData = () => {
  const cardData = [
    {
      c_id: "34465",
      store_name: "Moglix",
      store_slug: "moglix",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/moglix-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "CUR",
      currency_type: "₹",
      promo_code: "SINV300",
      title: "Exclusive Sale: Flat Rs 300 Off on Solar Inverters",
    },
    {
      c_id: "42643",
      store_name: "Avimee Herbal",
      store_slug: "avimee-herbal",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/avimee-herbal-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "IAMHAPPY100",
      title: "Exclusive Offer: Upto 60% Off + Extra Rs.100 Off On Your Order",
    },
    {
      c_id: "42638",
      store_name: "Ugaoo",
      store_slug: "ugaoo",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/ugaoo-coupon-promo-code.png",
      store_theme_color: "#fff6f4",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "SHOPPING10",
      title: "Exclusive Offer: Upto 50% Off + Extra 10% Off On Your  Order",
    },
    {
      c_id: "42636",
      store_name: "Neuherbs",
      store_slug: "neuherbs",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/neuherbs-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "SV10",
      title: "Republic Day Sale: Upto 65% Off + Extra 10% Off On Your Order",
    },
    {
      c_id: "42633",
      store_name: "Bloom",
      store_slug: "bloom",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/bloom-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "NEW10",
      title: "Sitewide Offer: Upto 50% Off + Extra 10% Off On Your Purchase",
    },
    {
      c_id: "34746",
      store_name: "Just Herbs",
      store_slug: "just-herbs",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/just-herbs-coupon-promo-code_7gj4LVy.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "JH15",
      title: "Republic Day Sale: Flat 50% Off + Extra 15% Off on Sitewide",
    },
    {
      c_id: "42631",
      store_name: "Jack & Jones Junior",
      store_slug: "jack-jones-junior",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/jack-jones-junior-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "JJJRNEW300",
      title: "Sitewide Offer: Upto 60% Off + Extra Rs.300 Off On Your Shopping",
    },
    {
      c_id: "42626",
      store_name: "Geekbuying",
      store_slug: "geekbuying",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/geekbuying-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "$",
      promo_code: "25SDSU1",
      title: "Year Of The Snake Sale: Upto 70% Off On Your Order",
    },
    {
      c_id: "19035",
      store_name: "Fossil",
      store_slug: "fossil",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/fossil-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "NEW10",
      title: "Exclusive Sale: Upto 40% Off  + Extra 15% Off on Your Purchase",
    },
    {
      c_id: "40920",
      store_name: "Marks & Spencer",
      store_slug: "marks-spencer",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/marks-spencer-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: null,
      title: "Spring Sale: Latest New Styles with Best Discounts",
    },
    {
      c_id: "42624",
      store_name: "Flo Mattress",
      store_slug: "flo-mattress",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/flo-mattress-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "INDIA",
      title: "Republic Day Sale: Upto 45% Off On Your Purchase",
    },
    {
      c_id: "2153",
      store_name: "Faces Canada",
      store_slug: "faces-canada",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/faces-canada-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "SAVE10",
      title:
        "Winter Sale: Upto 50% Off + Extra 10% Off + Free Gifts on All Orders",
    },
    {
      c_id: "41789",
      store_name: "Etchcraft Emporium",
      store_slug: "etchcraft-emporium",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/etchcraft-emporium-coupon-promo-code.png",
      store_theme_color: "#000000",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: null,
      title:
        "Valentines Day Offer: Flat 20% Off On Your Etchcraft Emporium Shopping",
    },
    {
      c_id: "42623",
      store_name: "Durfi",
      store_slug: "durfi",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/durfi-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "REPUBLICSALE",
      title:
        "Republic Day Sale: Flat 50% Off + Extra 5% Off + Free Gifts On Your Order",
    },
    {
      c_id: "39220",
      store_name: "Dermalogica",
      store_slug: "dermalogica",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/dermalogica-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "DAFF10",
      title: "Republic Day Sale: Upto 26% Off + Extra 10% Off on Your Cart",
    },
    {
      c_id: "3550",
      store_name: "Decathlon",
      store_slug: "decathlon",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/decathlon-coupon-promo-code.jpg",
      store_theme_color: "#1C74B3",
      discount_value: null,
      discount_type: "CUR",
      currency_type: "₹",
      promo_code: "NC200",
      title: "Exclusive Sale: Flat Rs.200 Off on your Purchase",
    },
    {
      c_id: "428",
      store_name: "Adidas",
      store_slug: "adidas",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/adidas-coupon-promo-code.jpg",
      store_theme_color: "#000000",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: null,
      title: "End-of-Season Sale: Flat 50% Off on Your Order",
    },
    {
      c_id: "24016",
      store_name: "Bummer",
      store_slug: "bummer",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/bummer-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "BUMMER20",
      title: "Exclusive Sale: Upto 60% Off + Extra 20% Off On Your  Purchase",
    },
    {
      c_id: "42618",
      store_name: "BigMuscles Nutrition",
      store_slug: "bigmuscles-nutrition",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/bigmuscles-nutrition-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "BM76",
      title: "Republic Day Sale: Upto 50% Off + Extra 7% Off On Your Purchase",
    },
    {
      c_id: "30933",
      store_name: "Beauty Barn",
      store_slug: "beauty-barn",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/beauty-barn-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: null,
      title: "Republic Day Sale - Upto 70% Off on Sale Items",
    },
    {
      c_id: "42615",
      store_name: "Aqualens",
      store_slug: "aqualens",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/aqualens-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "REPUBLIC20",
      title:
        "Republic Day Sale: Upto 40% Off + Extra 20% Off On Contact Lenses",
    },
    {
      c_id: "19442",
      store_name: "Adda247",
      store_slug: "adda247",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/adda247-coupon-promo-code_1giYB7m.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "DREAM",
      title:
        "Flat 77%  Off on all Live Classes, Test series, Video Courses, eBooks & Books",
    },
    {
      c_id: "31730",
      store_name: "Zouk",
      store_slug: "zouk",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/zouk-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "Z10",
      title: "Proudly Indian Sale: Upto 60% Off + Extra 10% Off on Your Cart",
    },
    {
      c_id: "42382",
      store_name: "YesStyle",
      store_slug: "yesstyle",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/yesstyle-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "SKIN25",
      title: "Exclusive Sale: Upto 45% Off + Extra 15% Off On Your Purchase",
    },
    {
      c_id: "31704",
      store_name: "Wow",
      store_slug: "wow",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/wow-coupon-promo-code.jpg",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "WOW",
      title: "11Th Birthday Offer: Buy 1 Get 1 Free on Sitewide",
    },
    {
      c_id: "42602",
      store_name: "Tripify",
      store_slug: "tripify",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/tripify-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "TRIPIFYUPI",
      title: "Get Upto 15% Off On Hotels And Flight Bookings",
    },
    {
      c_id: "31892",
      store_name: "Traya Health",
      store_slug: "traya-health",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/traya-health-coupon-promo-code.png",
      store_theme_color: "#414042",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: "TRY20",
      title: "Extra 20% OFF on Hair Growth Products + Hair Treatment Kits",
    },
    {
      c_id: "42012",
      store_name: "The Tribe Concepts",
      store_slug: "the-tribe-concepts",
      store_image:
        "https://ik.imagekit.io/c1suzwh62ew/tr:w-300,h-200/images/store/the-tribe-concepts-coupon-promo-code.png",
      store_theme_color: "#ffffff",
      discount_value: null,
      discount_type: "%",
      currency_type: "₹",
      promo_code: null,
      title: "Exclusive Sale: Flat 25% Off On Your Purchase",
    },
  ];

  return { cardData };
};

export default dummyData;
